
# Use the offical Golang image to create a build artifact.
# This is based on Debian and sets the GOPATH to /go.
# https://hub.docker.com/_/golang
FROM golang:1.12-alpine as builder

ENV CGO_ENABLED 0

# Allow Go to retreive the dependencies for the build step
RUN apk add --no-cache git

# Copy local code to the container image.
WORKDIR /go/src/github.com/keptn-contrib/prometheus-service
COPY . .

# Build the command inside the container.
# (You may fetch or manage dependencies here, either manually or with a tool like "godep".)
RUN CGO_ENABLED=0 GOOS=linux go build -v -gcflags="all=-N -l" -o prometheus-service

ARG KUBE_VERSION=1.14.1
RUN wget -q https://storage.googleapis.com/kubernetes-release/release/v$KUBE_VERSION/bin/linux/amd64/kubectl -O /bin/kubectl && \
  chmod +x /bin/kubectl

WORKDIR /go/src/
RUN go get github.com/go-delve/delve/cmd/dlv

WORKDIR /
ENV env=production
ADD manifests /manifests

EXPOSE 8080 40000

CMD ["/go/bin/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "exec", "/go/src/github.com/keptn-contrib/prometheus-service/prometheus-service"]
