apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: keptncontrib/prometheus-service
      docker:    # 	beta describes an artifact built from a Dockerfile.
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  kubectl:
    manifests:
    - deploy/service.yaml
