apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-service.fullname" . }}
  labels:
    {{- include "prometheus-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "prometheus-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-service.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheus-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: prometheus-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: METRICS_SCRAPE_PATH
              value: '/metrics'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
            - name: PROMETHEUS_NS
              value: '{{ .Values.prometheus.namespace }}'
            - name: PROMETHEUS_CM
              value: 'prometheus-server'
            - name: PROMETHEUS_LABELS
              value: 'component=server'
            - name: PROMETHEUS_ENDPOINT
              value: "{{ .Values.prometheus.endpoint }}"
            - name: PROMETHEUS_CONFIG_FILENAME
              value: 'prometheus.yml'
            - name: ALERT_MANAGER_CONFIG_FILENAME
              value: 'alertmanager.yml'
            - name: ALERT_MANAGER_CM
              value: 'prometheus-alertmanager'
            - name: ALERT_MANAGER_LABELS
              value: 'component=alertmanager'
            - name: ALERT_MANAGER_NS
              value: '{{ .Values.prometheus.namespace_am }}'
            - name: ALERT_MANAGER_TEMPLATE_CM
              value: 'alertmanager-templates'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SCRAPE_INTERVAL
              value: '{{ ((.Values.prometheus).scrapeInterval) | default "5s" }}'
        - name: distributor
          image: "{{ .Values.distributor.image.repository }}:{{ .Values.distributor.image.tag | default .Chart.AppVersion }}"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: {{ .Values.distributor.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "32Mi"
              cpu: "100m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.monitoring.configure,sh.keptn.event.configure-monitoring.triggered,sh.keptn.event.get-sli.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
            - name: PUBSUB_RECIPIENT_PATH
              value: '/events'
            - name: STAGE_FILTER
              value: "{{ .Values.distributor.stageFilter }}"
            - name: PROJECT_FILTER
              value: "{{ .Values.distributor.projectFilter }}"
            - name: SERVICE_FILTER
              value: "{{ .Values.distributor.serviceFilter }}"
            - name: DISTRIBUTOR_VERSION
              value: {{ .Values.distributor.image.tag | default .Chart.AppVersion }}
            - name: VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/version']
            - name: LOCATION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/component']
            - name: K8S_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- if .Values.remoteControlPlane.enabled }}
            - name: KEPTN_API_ENDPOINT
              value: "{{ .Values.remoteControlPlane.api.protocol }}://{{ .Values.remoteControlPlane.api.hostname }}/api"
            - name: KEPTN_API_TOKEN
              value: "{{ .Values.remoteControlPlane.api.token }}"
            - name: HTTP_SSL_VERIFY
              {{- $apiValidateTls := .Values.remoteControlPlane.api.apiValidateTls | ternary "true" "false" }}
              value: "{{ $apiValidateTls }}"
            {{- end }}
            {{- if (((.Values.distributor).config).queueGroup).enabled | default true }}
            - name: PUBSUB_GROUP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app.kubernetes.io/name']
            {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
