{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-service.serviceAccountName" . }}
  labels:
    {{- include "prometheus-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-create-prom-clusterrole
rules:
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - get
      - create
      - update
    resourceNames:
      - "prometheus"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-prom-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - nodes
      - nodes/proxy
      - pods
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - "ingresses"
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs: [ "/metrics" ]
    verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keptn-read-secret-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-prometheus-sli-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-read-secret-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-service.serviceAccountName" . }}
    namespace: keptn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-create-prom-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-create-prom-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-service.serviceAccountName" . }}
    namespace: keptn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keptn-prom-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keptn-prom-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-service.serviceAccountName" . }}
    namespace: keptn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-keptndomain-prom-service
  namespace: keptn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-keptndomain
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-service.serviceAccountName" . }}
    namespace: keptn

{{- end }}
