apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-prometheus-service
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-prometheus-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-prometheus-service
subjects:
  - kind: ServiceAccount
    name: keptn-prometheus-service
    namespace: keptn
