// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/keptn-contrib/prometheus-service/utils/prometheus (interfaces: PrometheusAPI)

// Package fake is a generated GoMock package.
package fake

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/prometheus/client_golang/api/prometheus/v1"
	model "github.com/prometheus/common/model"
)

// MockPrometheusAPI is a mock of PrometheusAPI interface.
type MockPrometheusAPI struct {
	ctrl     *gomock.Controller
	recorder *MockPrometheusAPIMockRecorder
}

// MockPrometheusAPIMockRecorder is the mock recorder for MockPrometheusAPI.
type MockPrometheusAPIMockRecorder struct {
	mock *MockPrometheusAPI
}

// NewMockPrometheusAPI creates a new mock instance.
func NewMockPrometheusAPI(ctrl *gomock.Controller) *MockPrometheusAPI {
	mock := &MockPrometheusAPI{ctrl: ctrl}
	mock.recorder = &MockPrometheusAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrometheusAPI) EXPECT() *MockPrometheusAPIMockRecorder {
	return m.recorder
}

// AlertManagers mocks base method.
func (m *MockPrometheusAPI) AlertManagers(arg0 context.Context) (v1.AlertManagersResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlertManagers", arg0)
	ret0, _ := ret[0].(v1.AlertManagersResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlertManagers indicates an expected call of AlertManagers.
func (mr *MockPrometheusAPIMockRecorder) AlertManagers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlertManagers", reflect.TypeOf((*MockPrometheusAPI)(nil).AlertManagers), arg0)
}

// Alerts mocks base method.
func (m *MockPrometheusAPI) Alerts(arg0 context.Context) (v1.AlertsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Alerts", arg0)
	ret0, _ := ret[0].(v1.AlertsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Alerts indicates an expected call of Alerts.
func (mr *MockPrometheusAPIMockRecorder) Alerts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Alerts", reflect.TypeOf((*MockPrometheusAPI)(nil).Alerts), arg0)
}

// Buildinfo mocks base method.
func (m *MockPrometheusAPI) Buildinfo(arg0 context.Context) (v1.BuildinfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Buildinfo", arg0)
	ret0, _ := ret[0].(v1.BuildinfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Buildinfo indicates an expected call of Buildinfo.
func (mr *MockPrometheusAPIMockRecorder) Buildinfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Buildinfo", reflect.TypeOf((*MockPrometheusAPI)(nil).Buildinfo), arg0)
}

// CleanTombstones mocks base method.
func (m *MockPrometheusAPI) CleanTombstones(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanTombstones", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanTombstones indicates an expected call of CleanTombstones.
func (mr *MockPrometheusAPIMockRecorder) CleanTombstones(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanTombstones", reflect.TypeOf((*MockPrometheusAPI)(nil).CleanTombstones), arg0)
}

// Config mocks base method.
func (m *MockPrometheusAPI) Config(arg0 context.Context) (v1.ConfigResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Config", arg0)
	ret0, _ := ret[0].(v1.ConfigResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Config indicates an expected call of Config.
func (mr *MockPrometheusAPIMockRecorder) Config(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Config", reflect.TypeOf((*MockPrometheusAPI)(nil).Config), arg0)
}

// DeleteSeries mocks base method.
func (m *MockPrometheusAPI) DeleteSeries(arg0 context.Context, arg1 []string, arg2, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeries", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeries indicates an expected call of DeleteSeries.
func (mr *MockPrometheusAPIMockRecorder) DeleteSeries(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeries", reflect.TypeOf((*MockPrometheusAPI)(nil).DeleteSeries), arg0, arg1, arg2, arg3)
}

// Flags mocks base method.
func (m *MockPrometheusAPI) Flags(arg0 context.Context) (v1.FlagsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flags", arg0)
	ret0, _ := ret[0].(v1.FlagsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Flags indicates an expected call of Flags.
func (mr *MockPrometheusAPIMockRecorder) Flags(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flags", reflect.TypeOf((*MockPrometheusAPI)(nil).Flags), arg0)
}

// LabelNames mocks base method.
func (m *MockPrometheusAPI) LabelNames(arg0 context.Context, arg1 []string, arg2, arg3 time.Time) ([]string, v1.Warnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LabelNames", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(v1.Warnings)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LabelNames indicates an expected call of LabelNames.
func (mr *MockPrometheusAPIMockRecorder) LabelNames(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LabelNames", reflect.TypeOf((*MockPrometheusAPI)(nil).LabelNames), arg0, arg1, arg2, arg3)
}

// LabelValues mocks base method.
func (m *MockPrometheusAPI) LabelValues(arg0 context.Context, arg1 string, arg2 []string, arg3, arg4 time.Time) (model.LabelValues, v1.Warnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LabelValues", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(model.LabelValues)
	ret1, _ := ret[1].(v1.Warnings)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LabelValues indicates an expected call of LabelValues.
func (mr *MockPrometheusAPIMockRecorder) LabelValues(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LabelValues", reflect.TypeOf((*MockPrometheusAPI)(nil).LabelValues), arg0, arg1, arg2, arg3, arg4)
}

// Metadata mocks base method.
func (m *MockPrometheusAPI) Metadata(arg0 context.Context, arg1, arg2 string) (map[string][]v1.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Metadata", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string][]v1.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Metadata indicates an expected call of Metadata.
func (mr *MockPrometheusAPIMockRecorder) Metadata(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Metadata", reflect.TypeOf((*MockPrometheusAPI)(nil).Metadata), arg0, arg1, arg2)
}

// Query mocks base method.
func (m *MockPrometheusAPI) Query(arg0 context.Context, arg1 string, arg2 time.Time) (model.Value, v1.Warnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.Value)
	ret1, _ := ret[1].(v1.Warnings)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockPrometheusAPIMockRecorder) Query(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPrometheusAPI)(nil).Query), arg0, arg1, arg2)
}

// QueryExemplars mocks base method.
func (m *MockPrometheusAPI) QueryExemplars(arg0 context.Context, arg1 string, arg2, arg3 time.Time) ([]v1.ExemplarQueryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryExemplars", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]v1.ExemplarQueryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryExemplars indicates an expected call of QueryExemplars.
func (mr *MockPrometheusAPIMockRecorder) QueryExemplars(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryExemplars", reflect.TypeOf((*MockPrometheusAPI)(nil).QueryExemplars), arg0, arg1, arg2, arg3)
}

// QueryRange mocks base method.
func (m *MockPrometheusAPI) QueryRange(arg0 context.Context, arg1 string, arg2 v1.Range) (model.Value, v1.Warnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryRange", arg0, arg1, arg2)
	ret0, _ := ret[0].(model.Value)
	ret1, _ := ret[1].(v1.Warnings)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryRange indicates an expected call of QueryRange.
func (mr *MockPrometheusAPIMockRecorder) QueryRange(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRange", reflect.TypeOf((*MockPrometheusAPI)(nil).QueryRange), arg0, arg1, arg2)
}

// Rules mocks base method.
func (m *MockPrometheusAPI) Rules(arg0 context.Context) (v1.RulesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rules", arg0)
	ret0, _ := ret[0].(v1.RulesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rules indicates an expected call of Rules.
func (mr *MockPrometheusAPIMockRecorder) Rules(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rules", reflect.TypeOf((*MockPrometheusAPI)(nil).Rules), arg0)
}

// Runtimeinfo mocks base method.
func (m *MockPrometheusAPI) Runtimeinfo(arg0 context.Context) (v1.RuntimeinfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Runtimeinfo", arg0)
	ret0, _ := ret[0].(v1.RuntimeinfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Runtimeinfo indicates an expected call of Runtimeinfo.
func (mr *MockPrometheusAPIMockRecorder) Runtimeinfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Runtimeinfo", reflect.TypeOf((*MockPrometheusAPI)(nil).Runtimeinfo), arg0)
}

// Series mocks base method.
func (m *MockPrometheusAPI) Series(arg0 context.Context, arg1 []string, arg2, arg3 time.Time) ([]model.LabelSet, v1.Warnings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Series", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]model.LabelSet)
	ret1, _ := ret[1].(v1.Warnings)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Series indicates an expected call of Series.
func (mr *MockPrometheusAPIMockRecorder) Series(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Series", reflect.TypeOf((*MockPrometheusAPI)(nil).Series), arg0, arg1, arg2, arg3)
}

// Snapshot mocks base method.
func (m *MockPrometheusAPI) Snapshot(arg0 context.Context, arg1 bool) (v1.SnapshotResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", arg0, arg1)
	ret0, _ := ret[0].(v1.SnapshotResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockPrometheusAPIMockRecorder) Snapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockPrometheusAPI)(nil).Snapshot), arg0, arg1)
}

// TSDB mocks base method.
func (m *MockPrometheusAPI) TSDB(arg0 context.Context) (v1.TSDBResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TSDB", arg0)
	ret0, _ := ret[0].(v1.TSDBResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TSDB indicates an expected call of TSDB.
func (mr *MockPrometheusAPIMockRecorder) TSDB(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TSDB", reflect.TypeOf((*MockPrometheusAPI)(nil).TSDB), arg0)
}

// Targets mocks base method.
func (m *MockPrometheusAPI) Targets(arg0 context.Context) (v1.TargetsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Targets", arg0)
	ret0, _ := ret[0].(v1.TargetsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Targets indicates an expected call of Targets.
func (mr *MockPrometheusAPIMockRecorder) Targets(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Targets", reflect.TypeOf((*MockPrometheusAPI)(nil).Targets), arg0)
}

// TargetsMetadata mocks base method.
func (m *MockPrometheusAPI) TargetsMetadata(arg0 context.Context, arg1, arg2, arg3 string) ([]v1.MetricMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TargetsMetadata", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]v1.MetricMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TargetsMetadata indicates an expected call of TargetsMetadata.
func (mr *MockPrometheusAPIMockRecorder) TargetsMetadata(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TargetsMetadata", reflect.TypeOf((*MockPrometheusAPI)(nil).TargetsMetadata), arg0, arg1, arg2, arg3)
}
